#!/bin/bash

files=$(git status --porcelain | sed s/^...//)

if [ $# -eq 1 ]; then
  editor=$1
else
  editor=echo
fi

if [[ "$editor" == *"vi"* ]]; then
  editor="$editor -p"
fi

command="$editor $files"

$command
